/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package EscapeRoom.GUI;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.JFrame;

/**
 *
 * @author Archontis
 */
public class CreditsPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreditsPanel
     */
    public CreditsPanel() {
        initComponents();
        this.setFocusable(true);
        this.addKeyListener(new CreditsPanel.myKeyListener());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escText = new javax.swing.JLabel();
        creditsBg = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        escText.setFont(new java.awt.Font("DPComic", 0, 18)); // NOI18N
        escText.setForeground(new java.awt.Color(255, 255, 255));
        escText.setText("Use ESC to go back to MAIN MENU");
        add(escText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        System.out.print(getClass());

        try {
            creditsBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EscapeRoom/guiAssets/creditsbg.png"))); // NOI18N
        }
        catch(Exception e){
            System.out.println("--------------------------");
            System.out.println("getClass().getResource(./)");
            System.out.println(getClass().getResource("././././"));
            System.out.println("--------------------------");
            System.out.println("getClass()");
            System.out.println(getClass());
            System.out.println("--------------------------");
        }
        add(creditsBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
    
    // --------- WARNING ----------
    // THIS METHOD IS USED FOR TESTING ONLY
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CreditsPanel testPanel = new EscapeRoom.GUI.CreditsPanel();
                
                // TEST FRAME CREATION
                JFrame f = new JFrame();
                f.setSize(1000, 556);
                f.setUndecorated(true);
                f.setVisible(true);
                
                // ADD PANEL
                f.getContentPane().add(testPanel);
                
            }
        });
    }
    // -----------------------------------
    
    /* KEY LISTENER CLASS START */
    class myKeyListener implements KeyListener {

        @Override
        public void keyTyped(KeyEvent e) {
            
        }

        @Override
        public void keyPressed(KeyEvent e) {
            if(e.getKeyCode() == java.awt.event.KeyEvent.VK_ESCAPE){
                System.out.println("ESC CREDITS");
                setVisible(false);
            }
        }

        @Override
        public void keyReleased(KeyEvent e) {
            
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel creditsBg;
    private javax.swing.JLabel escText;
    // End of variables declaration//GEN-END:variables
}
