/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package EscapeRoom.GUI;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;

/**
 *
 * @author Archontis
 */
public class ExitPanel extends javax.swing.JPanel {
    private MainFrame mainFrame;

    /**
     * Creates new form exitPanel
     */
    public ExitPanel() {
        initComponents();
        this.yesButton.addActionListener(new ButtonListener());
        this.noButton.addActionListener(new ButtonListener());
    }
    
    public void setMainFrame(MainFrame aFrame){
        this.mainFrame = aFrame;
    }
    
    public void setMainFramesPanelState(String aStateName){
        this.mainFrame.setPanelState(aStateName);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exitPromptLabel = new javax.swing.JLabel();
        noButton = new javax.swing.JButton();
        yesButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(224, 151, 34));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 35, 22), 5));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitPromptLabel.setFont(new java.awt.Font("DPComic", 0, 36)); // NOI18N
        exitPromptLabel.setForeground(new java.awt.Color(255, 255, 255));
        exitPromptLabel.setText("Are you sure you wanna to exit?");
        add(exitPromptLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        noButton.setFocusable(false);
        noButton.setBackground(new java.awt.Color(229, 55, 55));
        noButton.setFont(new java.awt.Font("DPComic", 0, 30)); // NOI18N
        noButton.setForeground(new java.awt.Color(255, 255, 255));
        noButton.setText("NO");
        noButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 35, 22), 4));
        noButton.setFocusable(false);
        add(noButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 140, 50));

        yesButton.setFocusable(false);
        yesButton.setBackground(new java.awt.Color(80, 184, 71));
        yesButton.setFont(new java.awt.Font("DPComic", 0, 30)); // NOI18N
        yesButton.setForeground(new java.awt.Color(255, 255, 255));
        yesButton.setText("YES");
        yesButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 35, 22), 4));
        yesButton.setFocusable(false);
        add(yesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 140, 50));
    }// </editor-fold>//GEN-END:initComponents
    
    // --------- WARNING ----------
    // THIS METHOD IS USED FOR TESTING ONLY
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ExitPanel testPanel = new EscapeRoom.GUI.ExitPanel();
                
                // TEST FRAME CREATION
                JFrame f = new JFrame();
                f.setSize(696, 220);
                f.setUndecorated(true);
                f.setVisible(true);
                
                // ADD PANEL
                f.getContentPane().add(testPanel);
                
            }
        });
    }
    // -----------------------------------
    
    
    class ButtonListener implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            if(e.getSource() == yesButton)
                System.exit(0);
            if(e.getSource() == noButton){
                setVisible(false);
                setMainFramesPanelState("home");
            }    
            //setFocusable(false);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exitPromptLabel;
    private javax.swing.JButton noButton;
    private javax.swing.JButton yesButton;
    // End of variables declaration//GEN-END:variables
}
