/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package EscapeRoom.GUI;

import EscapeRoom.GUI.MainFrame.ButtonListener;
import javax.swing.JButton;

/**
 *
 * @author Archontis
 */
public class FeatureUnavailablePanel extends javax.swing.JPanel {

    /**
     * Creates new form FeatureUnavailablePanel
     */
    public FeatureUnavailablePanel() {
        initComponents();
        this.setVisible(false);
    }
    
    public JButton getConfirmButton() {
        return this.confirmButton;
    }
    
    public void addListener(ButtonListener aListener){
        this.confirmButton.addActionListener(aListener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerLabel = new javax.swing.JLabel();
        commentLabel = new javax.swing.JLabel();
        confirmButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(224, 151, 34));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 35, 22), 5));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerLabel.setFont(new java.awt.Font("DPComic", 0, 25)); // NOI18N
        headerLabel.setForeground(new java.awt.Color(66, 35, 22));
        headerLabel.setText("Please use your imagination and believe this feature works!");
        add(headerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        commentLabel.setFont(new java.awt.Font("DPComic", 0, 30)); // NOI18N
        commentLabel.setForeground(new java.awt.Color(66, 35, 22));
        commentLabel.setText("Unfortunately our developers have not added this feature yet...");
        add(commentLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 770, 40));

        confirmButton.setBackground(new java.awt.Color(80, 184, 71));
        confirmButton.setFont(new java.awt.Font("DPComic", 0, 36)); // NOI18N
        confirmButton.setForeground(new java.awt.Color(255, 255, 255));
        confirmButton.setText("GOT IT");
        confirmButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 35, 22), 5));
        add(confirmButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 170, 60));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel commentLabel;
    private javax.swing.JButton confirmButton;
    private javax.swing.JLabel headerLabel;
    // End of variables declaration//GEN-END:variables
}
