/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package EscapeRoom.GUI;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JFrame;

/**
 *
 * @author Archontis
 */
public class HomeScreenPanel extends javax.swing.JPanel {

    /**
     * Creates new form HomeScreenPanel
     */
    public HomeScreenPanel() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tutorialLabel = new javax.swing.JLabel();
        startLabel = new javax.swing.JLabel();
        settingsLabel = new javax.swing.JLabel();
        creditsLabel = new javax.swing.JLabel();
        exitLabel = new javax.swing.JLabel();
        bgImage = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tutorialLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EscapeRoom/guiAssets/tutorialIcon.png"))); // NOI18N
        add(tutorialLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 110, 110));

        startLabel.setBackground(new java.awt.Color(255, 255, 255));
        startLabel.setFont(new java.awt.Font("DPComic", 0, 52)); // NOI18N
        startLabel.setForeground(new java.awt.Color(255, 255, 255));
        startLabel.setText("START");
        startLabel.addMouseListener(new myMouseListener());
        add(startLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 140, -1));

        settingsLabel.setBackground(new java.awt.Color(255, 255, 255));
        settingsLabel.setFont(new java.awt.Font("DPComic", 0, 52)); // NOI18N
        settingsLabel.setForeground(new java.awt.Color(255, 255, 255));
        settingsLabel.setText("SETTINGS");
        settingsLabel.setEnabled(false);
        settingsLabel.addMouseListener(new myMouseListener());
        add(settingsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 200, 60));

        creditsLabel.setBackground(new java.awt.Color(255, 255, 255));
        creditsLabel.setFont(new java.awt.Font("DPComic", 0, 52)); // NOI18N
        creditsLabel.setForeground(new java.awt.Color(255, 255, 255));
        creditsLabel.setText("CREDITS");
        creditsLabel.setEnabled(false);
        creditsLabel.addMouseListener(new myMouseListener());
        add(creditsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 180, -1));

        exitLabel.setBackground(new java.awt.Color(255, 255, 255));
        exitLabel.setFont(new java.awt.Font("DPComic", 0, 52)); // NOI18N
        exitLabel.setForeground(new java.awt.Color(255, 255, 255));
        exitLabel.setText("EXIT");
        exitLabel.setEnabled(false);
        exitLabel.addMouseListener(new myMouseListener());
        add(exitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, 100, -1));

        bgImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EscapeRoom/guiAssets/mainMenuBg.png"))); // NOI18N
        add(bgImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));
    }// </editor-fold>//GEN-END:initComponents

    
    /* MOUSE EVENT LISTENER CLASS START */
    class myMouseListener implements MouseListener {
        public void mouseClicked(MouseEvent e) {
            if(e.getSource() == startLabel)
                System.out.println("MOUSE CLICKED START");
            if(e.getSource() == settingsLabel)
                System.out.println("MOUSE CLICKED SETTINGS");
            if(e.getSource() == creditsLabel)
                System.out.println("MOUSE CLICKED CREDITS");
            if(e.getSource() == exitLabel)
                System.out.println("MOUSE CLICKED EXIT");
        }
        
        public void mouseEntered(MouseEvent e) {
            
        }
        
        public void mouseExited(MouseEvent e) {
            
        }

        @Override
        public void mousePressed(MouseEvent e) {
            
        }

        @Override
        public void mouseReleased(MouseEvent e) {
            
        }
    }
    /* MOUSE EVENT LISTENER CLASS END */
    
    
    // --------- WARNING ----------
    // THIS METHOD IS USED FOR TESTING ONLY
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HomeScreenPanel testPanel = new EscapeRoom.GUI.HomeScreenPanel();
                
                // TEST FRAME CREATION
                JFrame f = new JFrame();
                f.setSize(1000, 556);
                f.setUndecorated(true);
                f.setVisible(true);
                
                // ADD PANEL
                f.getContentPane().add(testPanel);
                
            }
        });
    }
    // -----------------------------------
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgImage;
    private javax.swing.JLabel creditsLabel;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JLabel settingsLabel;
    private javax.swing.JLabel startLabel;
    private javax.swing.JLabel tutorialLabel;
    // End of variables declaration//GEN-END:variables
}
