/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package EscapeRoom.GUI;

import EscapeRoom.Game;
import EscapeRoom.Game_Saves;
import EscapeRoom.Player;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Archontis
 */
public class MainFrame extends javax.swing.JFrame {
    // Properties Declaration
    private String navigationState = "none";
    private String panelState = "home";
    
    public MainFrame() {
        initComponents();
        
        // Set App Icon
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/EscapeRoom/guiAssets/icon.png")));
        
        this.addKeyListener(new myKeyListener());
    }
    
    public void setPanelState(String aStateName){
        this.panelState = aStateName;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        // Custom Font Creation
        try{
            GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
            Font dpComicFont = Font.createFont(Font.TRUETYPE_FONT, getClass().getResourceAsStream("/EscapeRoom/GUI/dpcomic.ttf"));
            ge.registerFont(dpComicFont);
        }
        catch(Exception e){
            e.printStackTrace();
        }
        mainPanel = new javax.swing.JPanel();
        egyptianRoom1 = new Room.EgyptianRoom();
        tutorialPanel = new EscapeRoom.GUI.TutorialPanel();
        newPlayerPanel = new EscapeRoom.GUI.newPlayerPanel();
        startGamePanel = new EscapeRoom.GUI.StartGamePanel();
        settingsPanel = new EscapeRoom.GUI.SettingsPanel();
        creditsPanel = new EscapeRoom.GUI.CreditsPanel();
        exitPromptPanel = new EscapeRoom.GUI.ExitPanel();
        loadGamePanel = new EscapeRoom.GUI.loadGamePanel();
        tutorialLabel = new javax.swing.JLabel();
        startLabel = new javax.swing.JLabel();
        settingsLabel = new javax.swing.JLabel();
        creditsLabel = new javax.swing.JLabel();
        exitLabel = new javax.swing.JLabel();
        bgImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Digital Escape Room");
        setCursor(Toolkit.getDefaultToolkit().
            createCustomCursor(
                Toolkit.getDefaultToolkit().getImage(getClass().getResource("/EscapeRoom/guiAssets/cursor.png")),
                new Point(0,0),"custom cursor"
            ));
            setUndecorated(true);
            setResizable(false);

            mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            egyptianRoom1.setVisible(false);
            mainPanel.add(egyptianRoom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 950, 650));

            tutorialPanel.setVisible(false);
            mainPanel.add(tutorialPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 720));

            newPlayerPanel.setVisible(false);
            newPlayerPanel.addListenerToButton(new ButtonListener());
            mainPanel.add(newPlayerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

            startGamePanel.setVisible(false);
            startGamePanel.addListenerToButtons(new ButtonListener());
            mainPanel.add(startGamePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 743, 395));

            settingsPanel.setVisible(false);
            settingsPanel.setMainFrame(this);
            settingsPanel.getFeaturePanel().addListener(new ButtonListener());
            mainPanel.add(settingsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 700));

            creditsPanel.setVisible(false);
            mainPanel.add(creditsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 720));

            exitPromptPanel.setVisible(false);
            exitPromptPanel.setMainFrame(this);
            mainPanel.add(exitPromptPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 700, 180));

            loadGamePanel.setVisible(false);
            mainPanel.add(loadGamePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

            tutorialLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EscapeRoom/guiAssets/tutorialIcon.png"))); // NOI18N
            tutorialLabel.addMouseListener(new myMouseListener());
            mainPanel.add(tutorialLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 110, 110));

            startLabel.setBackground(new java.awt.Color(255, 255, 255));
            startLabel.setFont(new java.awt.Font("DPComic", 0, 52)); // NOI18N
            startLabel.setForeground(new java.awt.Color(255, 255, 255));
            startLabel.setText("START");
            startLabel.setEnabled(false);
            startLabel.addMouseListener(new myMouseListener());
            mainPanel.add(startLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 140, -1));

            settingsLabel.setBackground(new java.awt.Color(255, 255, 255));
            settingsLabel.setFont(new java.awt.Font("DPComic", 0, 52)); // NOI18N
            settingsLabel.setForeground(new java.awt.Color(255, 255, 255));
            settingsLabel.setText("SETTINGS");
            settingsLabel.setEnabled(false);
            settingsLabel.setFocusable(false);
            settingsLabel.addMouseListener(new myMouseListener());
            mainPanel.add(settingsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 200, 60));

            creditsLabel.setBackground(new java.awt.Color(255, 255, 255));
            creditsLabel.setFont(new java.awt.Font("DPComic", 0, 52)); // NOI18N
            creditsLabel.setForeground(new java.awt.Color(255, 255, 255));
            creditsLabel.setText("CREDITS");
            creditsLabel.setEnabled(false);
            creditsLabel.addMouseListener(new myMouseListener());
            mainPanel.add(creditsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 180, -1));

            exitLabel.setBackground(new java.awt.Color(255, 255, 255));
            exitLabel.setFont(new java.awt.Font("DPComic", 0, 52)); // NOI18N
            exitLabel.setForeground(new java.awt.Color(255, 255, 255));
            exitLabel.setText("EXIT");
            exitLabel.setEnabled(false);
            exitLabel.addMouseListener(new myMouseListener());
            mainPanel.add(exitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 480, 100, -1));

            bgImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EscapeRoom/guiAssets/mainMenuBg.png"))); // NOI18N
            mainPanel.add(bgImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 720));

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            );

            pack();
            setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents
    
    private void disableAllLabels() {
       startLabel.setEnabled(false);
       settingsLabel.setEnabled(false);
       creditsLabel.setEnabled(false);
       exitLabel.setEnabled(false);
    }
    
    /* This Methods are used from the Listeners */
    // Methods for Key Listener
    public void navigateUpKey() {
        // Check the pointer state
        switch (navigationState) {
            case "none":
                // Change the state
                navigationState = "start";
                // Disable Start Label and Enable Exit Label
                startLabel.setEnabled(true);
                break;
                
            case "start":
                // Change the state
                navigationState = "exit";
                // Disable Start Label and Enable Exit Label
                exitLabel.setEnabled(true);
                startLabel.setEnabled(false);
                break;
                
            case "settings":
                // Change the state
                navigationState = "start";
                // Disable Credits Label and Enable Start Label
                startLabel.setEnabled(true);
                settingsLabel.setEnabled(false);
                break;
                
            case "credits":
                // Change the state
                navigationState = "settings";
                // Disable Credits Label and Enable Start Label
                settingsLabel.setEnabled(true);
                creditsLabel.setEnabled(false);
                break;
            case "exit":
                // Change the state
                navigationState = "credits";
                // Disable Credits Label and Enable Start Label
                creditsLabel.setEnabled(true);
                exitLabel.setEnabled(false);
                break;
        }
    }
    
    public void navigateDownKey(){
        switch (navigationState) {
            case "none":
                navigationState="start";
                startLabel.setEnabled(true);
                break;
        
            case "start":
                // Change the state
                navigationState = "settings";
                // Disable Start Label and Enable Credits Label
                settingsLabel.setEnabled(true);
                startLabel.setEnabled(false);
                break;
            
            case "settings":
                // Change the state
                navigationState = "credits";
                // Disable Settings Label and Enable Credits Label
                creditsLabel.setEnabled(true);
                settingsLabel.setEnabled(false);
                break;
        
            case "credits":
                // Change the state
                navigationState = "exit";
                // Disable Start Label and Enable Exit Label
                exitLabel.setEnabled(true);
                creditsLabel.setEnabled(false);
                break;
        
            case "exit":
                // Change the state
                navigationState = "start";
                // Disable Start Label and Enable Exit Label
                startLabel.setEnabled(true);
                exitLabel.setEnabled(false);     
                break;
        } 
    }
    
    public void enterKeyPressed(){
        switch (navigationState) {
            case "start":
                panelState = "startGame";
                this.egyptianRoom1.setVisible(true);
                break;
            case "settings":
                panelState = "settings";
                settingsPanel.setVisible(true);
                // Give focus to SettingsPanel so its action listener works
                settingsPanel.requestFocus();
                break;
            case "credits":
                panelState = "credits";
                creditsPanel.setVisible(true);
                break;
            case "exit":
                panelState = "exit";
                exitPromptPanel.setVisible(true);
                break;
        }
    }
    
    public void escapeKeyPressed(){
        switch (panelState) {
            case "tutorial":
                panelState = "home";
                tutorialPanel.setVisible(false);
            case "startGame":
                panelState = "home";
                startGamePanel.setVisible(false);
            case "loadGame":
                panelState = "home";
                loadGamePanel.setVisible(false);
            case "newPlayer":
                panelState = "home";
                newPlayerPanel.getPlayerNameField().setText("Player");
                newPlayerPanel.setVisible(false);
            case "settings":
                panelState = "home";
                settingsPanel.setVisible(false);
                settingsPanel.getFeaturePanel().setVisible(false);
            case "credits":
                panelState = "home";
                creditsPanel.setVisible(false);
                break;
            case "exit":
                panelState = "home";
                exitPromptPanel.setVisible(false);
                break;
        }
    }
    
    // Methods for Mouse Listener
    public void homePanelMouseClicked(MouseEvent e){
        if(e.getSource() == startLabel){
            panelState = "startGame";
            this.egyptianRoom1.setVisible(true);
        }
        if(e.getSource() == settingsLabel){
             panelState = "settings";
            settingsPanel.setVisible(true);
            this.requestFocus();
        }   
        if(e.getSource() == creditsLabel){
             panelState = "credits";
            creditsPanel.setVisible(true);
        }   
        if(e.getSource() == exitLabel){
            panelState = "exit";
            exitPromptPanel.setVisible(true);
        }
        
        if(e.getSource() == tutorialLabel){
            this.tutorialPanel.setVisible(true);
            this.panelState = "tutorial";
            this.requestFocus();
        }
    }
    
    public void homePanelMouseEntered(MouseEvent e){
        if(e.getSource() == startLabel){
            disableAllLabels();
            startLabel.setEnabled(true);
            navigationState = "start";
        }
            
        if(e.getSource() == settingsLabel){
            disableAllLabels();
            settingsLabel.setEnabled(true);
            navigationState = "settings";
        }
                
        if(e.getSource() == creditsLabel){
            disableAllLabels();
            creditsLabel.setEnabled(true);
            navigationState = "credits";
        }
                
        if(e.getSource() == exitLabel){
            disableAllLabels();
            exitLabel.setEnabled(true);
            navigationState = "exit";
        }  
        
        if(e.getSource() == tutorialLabel){
            this.tutorialLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EscapeRoom/guiAssets/tutorialIconHover.png")));
        }
    }
    
    public void homePanelMouseExited(MouseEvent e){
        if(e.getSource() == startLabel){
            startLabel.setEnabled(false);
            navigationState = "none";
        }
            
        if(e.getSource() == settingsLabel){
            settingsLabel.setEnabled(false);
            navigationState = "none";
        }
            
        if(e.getSource() == creditsLabel){
            creditsLabel.setEnabled(false);
            navigationState = "none";
        }
            
        if(e.getSource() == exitLabel){
            exitLabel.setEnabled(false);
            navigationState = "none";
        }
        
        if(e.getSource() == tutorialLabel){
            this.tutorialLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EscapeRoom/guiAssets/tutorialIcon.png")));
        }
    }
    
    // Methods for Button Listener 
    public void startGamePanelActionPerformed(ActionEvent e){
        JButton loadButton = this.startGamePanel.getLoadButton();
        JButton newButton = this.startGamePanel.getNewButton();
        
        if(e.getSource() == loadButton){
            panelState = "loadGame";
            startGamePanel.setVisible(false);
            loadGamePanel.setVisible(true);
            requestFocus();
        }
        else if (e.getSource() == newButton){
            panelState = "newPlayer";
            startGamePanel.setVisible(false);
            newPlayerPanel.setVisible(true);
            requestFocus();
        }
    }
    
    public void SettingsPanelActionPerformed(ActionEvent e) {
        FeatureUnavailablePanel featureUnavalablePanel = this.settingsPanel.getFeaturePanel();
        JButton confirmButton = featureUnavalablePanel.getConfirmButton();
        
        if(e.getSource() == confirmButton){
            featureUnavalablePanel.setVisible(false);
            requestFocus();
        }
    }
    
    
    // ---------- Key Listener Class START ---------- //
    class myKeyListener implements KeyListener {

        @Override
        public void keyTyped(KeyEvent e) {
            
        }

        @Override
        public void keyPressed(KeyEvent e) {
            // ---- MENU NAVIGATION ----
            // If UP KEY is pressed
            if(e.getKeyCode() == java.awt.event.KeyEvent.VK_UP){
                navigateUpKey();
            }
            
            // If DOWN KEY is pressed
            if(e.getKeyCode() == java.awt.event.KeyEvent.VK_DOWN){
                navigateDownKey();
            }
            
            // ---- USER CONFIRMATION ACTION ----
            if(e.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
                enterKeyPressed();
            }
            
            // ---- USER ESCAPE ACTION ----
            if(e.getKeyCode() == java.awt.event.KeyEvent.VK_ESCAPE){
                escapeKeyPressed();
            }
        }

        @Override
        public void keyReleased(KeyEvent e){}
        
    }
    // ---------- Key Listener Class END ---------- //
    
    // ---------- Mouse Listener Class START ---------- //
    class myMouseListener implements MouseListener {
        @Override
        public void mouseClicked(MouseEvent e) {
            if(panelState.equalsIgnoreCase("home"))
               homePanelMouseClicked(e);
        }
        
        @Override
        public void mouseEntered(MouseEvent e) {
              homePanelMouseEntered(e);
        }
        
        @Override
        public void mouseExited(MouseEvent e) {
            homePanelMouseExited(e);
                
        }

        @Override
        public void mousePressed(MouseEvent e) {
            
                
        }

        @Override
        public void mouseReleased(MouseEvent e) {
            
        }
    }
    // ---------- Mouse Listener Class END ---------- //
    
    // ---------- Button Listener Class START ---------- //
    class ButtonListener implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent e) {
            startGamePanelActionPerformed(e);
            SettingsPanelActionPerformed(e);
        }
        
    }
    // ---------- Button Listener Class END ---------- //
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgImage;
    private javax.swing.JLabel creditsLabel;
    private EscapeRoom.GUI.CreditsPanel creditsPanel;
    private Room.EgyptianRoom egyptianRoom1;
    private javax.swing.JLabel exitLabel;
    private EscapeRoom.GUI.ExitPanel exitPromptPanel;
    private EscapeRoom.GUI.loadGamePanel loadGamePanel;
    private javax.swing.JPanel mainPanel;
    private EscapeRoom.GUI.newPlayerPanel newPlayerPanel;
    private javax.swing.JLabel settingsLabel;
    private EscapeRoom.GUI.SettingsPanel settingsPanel;
    private EscapeRoom.GUI.StartGamePanel startGamePanel;
    private javax.swing.JLabel startLabel;
    private javax.swing.JLabel tutorialLabel;
    private EscapeRoom.GUI.TutorialPanel tutorialPanel;
    // End of variables declaration//GEN-END:variables
}
