/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package EscapeRoom.GUI;
import EscapeRoom.*;
import EscapeRoom.GUI.MainFrame.ButtonListener;
import java.awt.Point;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Archontis
 */
public class newPlayerPanel extends javax.swing.JPanel {
    private Player player;

    /**
     * Creates new form newPlayerPanel
     */
    public newPlayerPanel() {
        initComponents();
    }
    
    public JButton getCreatePlayerButton(){
        return this.createPlayerButton;
    }
    
    public JTextField getPlayerNameField(){
        return this.playerNameField;
    }
    
    public String getTextfieldText(){
        return this.playerNameField.getText();
    }
    
    public void addListenerToButton(ButtonListener aListener) {
        this.createPlayerButton.addActionListener(aListener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createPlayerButton = new javax.swing.JButton();
        playerNameField = new javax.swing.JTextField();
        newPlayerHeader = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createPlayerButton.setBackground(new java.awt.Color(224, 151, 34));
        createPlayerButton.setFont(new java.awt.Font("DPComic", 0, 36)); // NOI18N
        createPlayerButton.setForeground(new java.awt.Color(255, 255, 255));
        createPlayerButton.setText("START");
        createPlayerButton.setAlignmentY(0.0F);
        createPlayerButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 35, 22), 5));
        // Custom Cursor
        createPlayerButton.setCursor(Toolkit.getDefaultToolkit().
            createCustomCursor(
                Toolkit.getDefaultToolkit().getImage(getClass().getResource("/EscapeRoom/guiAssets/cursor.png")),
                new Point(0,0),"custom cursor"
            )
        );
        createPlayerButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(createPlayerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 190, 60));

        playerNameField.setBackground(new java.awt.Color(40, 32, 30));
        playerNameField.setFont(new java.awt.Font("DPComic", 0, 45)); // NOI18N
        playerNameField.setForeground(new java.awt.Color(255, 255, 255));
        playerNameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        playerNameField.setText("Player");
        playerNameField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 151, 34), 5));
        playerNameField.setMargin(new java.awt.Insets(10, 10, 10, 10));
        playerNameField.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        playerNameField.setSelectionColor(new java.awt.Color(224, 151, 34));
        add(playerNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 430, 70));

        newPlayerHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EscapeRoom/guiAssets/newplayerbg.png"))); // NOI18N
        add(newPlayerHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createPlayerButton;
    private javax.swing.JLabel newPlayerHeader;
    private javax.swing.JTextField playerNameField;
    // End of variables declaration//GEN-END:variables
}
