/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package EscapeRoom.GUI;

import EscapeRoom.Game;
import EscapeRoom.Game_Saves;

/**
 *
 * @author Archontis
 */
public class testFrame extends javax.swing.JFrame {
    private Game game;
    private int roomNo = 0;

    /**
     * Creates new form testFrame
     */
    public testFrame(Game aGame) {
        this.game = aGame;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        playerLabel = new javax.swing.JLabel();
        levelLabel = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(224, 151, 34));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerLabel.setFont(new java.awt.Font("DPComic", 0, 60)); // NOI18N
        headerLabel.setForeground(new java.awt.Color(23, 15, 12));
        headerLabel.setText("NEW GAME STARTED");
        mainPanel.add(headerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 460, -1));

        playerLabel.setFont(new java.awt.Font("DPComic", 0, 48)); // NOI18N
        playerLabel.setForeground(new java.awt.Color(23, 15, 12));
        playerLabel.setText(this.game.getPlayer().getPlayerName());
        mainPanel.add(playerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));

        levelLabel.setFont(new java.awt.Font("DPComic", 0, 48)); // NOI18N
        levelLabel.setForeground(new java.awt.Color(23, 15, 12));
        levelLabel.setText("Level");
        mainPanel.add(levelLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, -1));

        saveButton.setText("SAVE");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        mainPanel.add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 190, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        Game_Saves gameSave = new Game_Saves();
        gameSave.setPlayer(this.game.getPlayer());
        gameSave.setRoom(game.getRoomByIndex(roomNo));
        
        try{
            gameSave.saveToFile("saves.txt");
        }
        catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_saveButtonActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(testFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(testFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(testFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(testFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new testFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel headerLabel;
    private javax.swing.JLabel levelLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel playerLabel;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
