/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Room;

import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JFrame;

/**
 *
 * @author 30694
 */
public class EgyptianRoom extends javax.swing.JPanel {

    /**
     * Creates new form EgyptianRoom
     */
    public EgyptianRoom() {
        initComponents();
    }
    
    private void rockTriggerMouseEntered(){
        this.rockTrigger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoomAssets/rock_2.png")));
    }
    
    private void rockTriggerMouseExited(){
        this.rockTrigger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoomAssets/rock_1.png")));
    }
    
    private void rockTriggerMouseClicked(){
        this.riddleOnePanel.showPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        riddleThreePanel = new RiddlesFrame.RiddleEg3();
        riddleOnePanel = new RiddlesFrame.RiddleEg1();
        riddleTwoPanel = new RiddlesFrame.RiddleEg2();
        rockTrigger = new javax.swing.JLabel();
        doorImage = new javax.swing.JLabel();
        torch = new javax.swing.JLabel();
        plantOneImage = new javax.swing.JLabel();
        plant1 = new javax.swing.JLabel();
        backgroundImage = new javax.swing.JLabel();

        setBackground(new java.awt.Color(41, 26, 5));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        riddleThreePanel.setVisible(false);
        add(riddleThreePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        riddleOnePanel.hide();
        riddleOnePanel.setNextRiddlePanel(riddleTwoPanel);
        add(riddleOnePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        riddleTwoPanel.hidePanel();
        riddleTwoPanel.setNextRiddlePanel(riddleThreePanel);
        add(riddleTwoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 790, 280));

        rockTrigger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoomAssets/rock_1.png"))); // NOI18N
        rockTrigger.addMouseListener(new myMouseListener());
        add(rockTrigger, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, -1, -1));

        doorImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoomAssets/gate_a.png"))); // NOI18N
        doorImage.setText("jLabel3");
        add(doorImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 280, 390));

        torch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoomAssets/lampa.png"))); // NOI18N
        add(torch, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 340, 50, -1));

        plantOneImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoomAssets/glastra2.png"))); // NOI18N
        plantOneImage.setText("jLabel2");
        add(plantOneImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, 110, -1));

        plant1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoomAssets/glastra1.png"))); // NOI18N
        plant1.setText("jLabel4");
        add(plant1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 440, 140, -1));

        backgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoomAssets/background1_.png"))); // NOI18N
        add(backgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, -1));
    }// </editor-fold>//GEN-END:initComponents
    
    
    // --------- WARNING ----------
    // THIS METHOD IS USED FOR TESTING ONLY
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EgyptianRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EgyptianRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EgyptianRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EgyptianRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EgyptianRoom testPanel = new EgyptianRoom();
                
                // TEST FRAME CREATION
                JFrame f = new JFrame();
                f.setSize(949, 648);
                
                f.setVisible(true);
                
                // ADD PANEL
                f.getContentPane().add(testPanel);
                
            }
        });
    }
    // -----------------------------------
    
    class myMouseListener implements MouseListener {

        @Override
        public void mouseClicked(MouseEvent e) {
            if(e.getSource() == rockTrigger)
                rockTriggerMouseClicked();
        }

        @Override
        public void mousePressed(MouseEvent e) {
            
        }

        @Override
        public void mouseReleased(MouseEvent e) {
            
        }

        @Override
        public void mouseEntered(MouseEvent e) {
            if(e.getSource() == rockTrigger)
                rockTriggerMouseEntered();
        }

        @Override
        public void mouseExited(MouseEvent e) {
            if(e.getSource() == rockTrigger)
                rockTriggerMouseExited();
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundImage;
    private javax.swing.JLabel doorImage;
    private javax.swing.JLabel plant1;
    private javax.swing.JLabel plantOneImage;
    private RiddlesFrame.RiddleEg1 riddleOnePanel;
    private RiddlesFrame.RiddleEg3 riddleThreePanel;
    private RiddlesFrame.RiddleEg2 riddleTwoPanel;
    private javax.swing.JLabel rockTrigger;
    private javax.swing.JLabel torch;
    // End of variables declaration//GEN-END:variables
}
