/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package RiddlesFrame;

/**
 *
 * @author Archontis
 */
public class doorExitPanel extends javax.swing.JPanel {
    private EndPanel winPanel;
    /**
     * Creates new form doorExitPanel
     */
    public doorExitPanel() {
        initComponents();
    }
    
    public void hidePanel(){
        this.setVisible(false);
    }
    
    public void showPanel(){
        this.setVisible(true);
    }
    
    public void setEndPanel(EndPanel aPanel){
        this.winPanel = aPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        doorImage = new javax.swing.JLabel();
        headerLabel = new javax.swing.JLabel();
        inputOne = new javax.swing.JTextField();
        inputTwo = new javax.swing.JTextField();
        inputThree = new javax.swing.JTextField();
        inputFour = new javax.swing.JTextField();
        inputFive = new javax.swing.JTextField();
        headerLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        doorImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RoomAssets/version__8_.png"))); // NOI18N
        add(doorImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        headerLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        headerLabel.setForeground(new java.awt.Color(255, 255, 255));
        headerLabel.setText("Hint: Παρατήρησε την πόρτα, θυμήσου τον προηγούμενο γρίφο");
        add(headerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, -1, 60));

        inputOne.setText("-");
        add(inputOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 50, 70));

        inputTwo.setText("-");
        add(inputTwo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 50, 70));

        inputThree.setText("-");
        add(inputThree, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 50, 70));

        inputFour.setText("-");
        add(inputFour, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, 50, 70));

        inputFive.setText("-");
        add(inputFive, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, 50, 70));

        headerLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        headerLabel1.setForeground(new java.awt.Color(255, 255, 255));
        headerLabel1.setText("Βάλε κωδικό για να ανοίξεις την πόρτα");
        add(headerLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, -1, -1));

        jButton1.setText("ΣΟΥΣΑΜΙ ΑΝΟΙΞΕ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 250, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String inputPin = inputOne.getText() + inputTwo.getText() + inputThree.getText() + inputFour.getText() + inputFive.getText();
        String correctPin = "35342";
        
        if(inputPin.equalsIgnoreCase(correctPin)){
            this.hidePanel();
            this.winPanel.setVisible(true);
            this.winPanel.setCommentText("ΚΕΡΔΙΣΕΣ");
        } else{
            this.hidePanel();
            this.winPanel.setVisible(true);
            this.winPanel.setCommentText("ΕΧΑΣΕΣ");
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel doorImage;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JLabel headerLabel1;
    private javax.swing.JTextField inputFive;
    private javax.swing.JTextField inputFour;
    private javax.swing.JTextField inputOne;
    private javax.swing.JTextField inputThree;
    private javax.swing.JTextField inputTwo;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
