/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package RiddlesFrame;

import Room.EgyptianRoom;

/**
 *
 * @author Archontis
 */
public class EndPanel extends javax.swing.JPanel {
    private EgyptianRoom roomToClose;

    /**
     * Creates new form EndPanel
     */
    public EndPanel() {
        initComponents();
    }
    
    
    public void setRoomToClose(EgyptianRoom aRoom){
        this.roomToClose = aRoom;
    }
    
    public void setCommentText(String aText){
        this.comment.setText(aText);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comment = new javax.swing.JLabel();
        headerLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comment.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        comment.setForeground(new java.awt.Color(255, 255, 255));
        comment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        comment.setText("ΕΧΑΣΕΣ");
        add(comment, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 350, -1));

        headerLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        headerLabel.setForeground(new java.awt.Color(255, 255, 255));
        headerLabel.setText("Το παιχνίδι τελείωσε!");
        add(headerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        jButton1.setText("ΕΠΙΣΤΡΟΦΗ ΣΤΟ ΜΕΝΟΥ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 200, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.roomToClose.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel comment;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
