/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package RiddlesFrame;

/**
 *
 * @author 30694
 */
public class RiddleGr1 extends javax.swing.JPanel {

    /**
     * Creates new form RiddleGr1
     */
    public RiddleGr1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jComboBox7 = new javax.swing.JComboBox<>();
        jComboBox8 = new javax.swing.JComboBox<>();
        jComboBox9 = new javax.swing.JComboBox<>();
        jComboBox10 = new javax.swing.JComboBox<>();
        jComboBox11 = new javax.swing.JComboBox<>();
        jComboBox12 = new javax.swing.JComboBox<>();
        jComboBox13 = new javax.swing.JComboBox<>();
        jComboBox14 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jTextPane1);

        setBackground(new java.awt.Color(204, 102, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesR/hercules7.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 150, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesR/hercules2.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 150, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesR/hercules1.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 150, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesR/hercules8.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 150, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesR/hercules4.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 150, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesR/hercules10.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, 150, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesR/hercules5.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 150, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesR/hercules3.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, 150, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesR/hercules11.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 480, 150, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesR/hercules9.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 480, 150, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesR/hercules6.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 480, 150, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesR/hercules12.jpg"))); // NOI18N
        jLabel12.setText("jLabel12");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 480, 150, -1));

        jComboBox1.setBackground(new java.awt.Color(0, 0, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "'Αθλος 1", "'Αθλος 2", "'Αθλος 3", "'Αθλος 4", "'Αθλος 5", "'Αθλος 6", "'Αθλος 7", "'Αθλος 8", "'Αθλος 9", "'Αθλος 10", "'Αθλος 11", "'Αθλος 12" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 180, 90, -1));

        jComboBox4.setBackground(new java.awt.Color(0, 0, 0));
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "'Αθλος 1", "'Αθλος 2", "'Αθλος 3", "'Αθλος 4", "'Αθλος 5", "'Αθλος 6", "'Αθλος 7", "'Αθλος 8", "'Αθλος 9", "'Αθλος 10", "'Αθλος 11", "'Αθλος 12" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(576, 180, 90, -1));

        jComboBox5.setBackground(new java.awt.Color(0, 0, 0));
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "'Αθλος 1", "'Αθλος 2", "'Αθλος 3", "'Αθλος 4", "'Αθλος 5", "'Αθλος 6", "'Αθλος 7", "'Αθλος 8", "'Αθλος 9", "'Αθλος 10", "'Αθλος 11", "'Αθλος 12" }));
        add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(746, 180, 90, -1));

        jComboBox6.setBackground(new java.awt.Color(0, 0, 0));
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "'Αθλος 1", "'Αθλος 2", "'Αθλος 3", "'Αθλος 4", "'Αθλος 5", "'Αθλος 6", "'Αθλος 7", "'Αθλος 8", "'Αθλος 9", "'Αθλος 10", "'Αθλος 11", "'Αθλος 12" }));
        add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(916, 180, 90, -1));

        jComboBox7.setBackground(new java.awt.Color(0, 0, 0));
        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "'Αθλος 1", "'Αθλος 2", "'Αθλος 3", "'Αθλος 4", "'Αθλος 5", "'Αθλος 6", "'Αθλος 7", "'Αθλος 8", "'Αθλος 9", "'Αθλος 10", "'Αθλος 11", "'Αθλος 12" }));
        add(jComboBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 90, -1));

        jComboBox8.setBackground(new java.awt.Color(0, 0, 0));
        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "'Αθλος 1", "'Αθλος 2", "'Αθλος 3", "'Αθλος 4", "'Αθλος 5", "'Αθλος 6", "'Αθλος 7", "'Αθλος 8", "'Αθλος 9", "'Αθλος 10", "'Αθλος 11", "'Αθλος 12" }));
        add(jComboBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 90, -1));

        jComboBox9.setBackground(new java.awt.Color(0, 0, 0));
        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "'Αθλος 1", "'Αθλος 2", "'Αθλος 3", "'Αθλος 4", "'Αθλος 5", "'Αθλος 6", "'Αθλος 7", "'Αθλος 8", "'Αθλος 9", "'Αθλος 10", "'Αθλος 11", "'Αθλος 12" }));
        add(jComboBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 440, 90, -1));

        jComboBox10.setBackground(new java.awt.Color(0, 0, 0));
        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "'Αθλος 1", "'Αθλος 2", "'Αθλος 3", "'Αθλος 4", "'Αθλος 5", "'Αθλος 6", "'Αθλος 7", "'Αθλος 8", "'Αθλος 9", "'Αθλος 10", "'Αθλος 11", "'Αθλος 12" }));
        jComboBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox10ActionPerformed(evt);
            }
        });
        add(jComboBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(576, 440, 90, -1));

        jComboBox11.setBackground(new java.awt.Color(0, 0, 0));
        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "'Αθλος 1", "'Αθλος 2", "'Αθλος 3", "'Αθλος 4", "'Αθλος 5", "'Αθλος 6", "'Αθλος 7", "'Αθλος 8", "'Αθλος 9", "'Αθλος 10", "'Αθλος 11", "'Αθλος 12" }));
        add(jComboBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(746, 440, 90, -1));

        jComboBox12.setBackground(new java.awt.Color(0, 0, 0));
        jComboBox12.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "'Αθλος 1", "'Αθλος 2", "'Αθλος 3", "'Αθλος 4", "'Αθλος 5", "'Αθλος 6", "'Αθλος 7", "'Αθλος 8", "'Αθλος 9", "'Αθλος 10", "'Αθλος 11", "'Αθλος 12" }));
        add(jComboBox12, new org.netbeans.lib.awtextra.AbsoluteConstraints(916, 440, 90, -1));

        jComboBox13.setBackground(new java.awt.Color(0, 0, 0));
        jComboBox13.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "'Αθλος 1", "'Αθλος 2", "'Αθλος 3", "'Αθλος 4", "'Αθλος 5", "'Αθλος 6", "'Αθλος 7", "'Αθλος 8", "'Αθλος 9", "'Αθλος 10", "'Αθλος 11", "'Αθλος 12" }));
        jComboBox13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox13ActionPerformed(evt);
            }
        });
        add(jComboBox13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 90, -1));

        jComboBox14.setBackground(new java.awt.Color(0, 0, 0));
        jComboBox14.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "'Αθλος 1", "'Αθλος 2", "'Αθλος 3", "'Αθλος 4", "'Αθλος 5", "'Αθλος 6", "'Αθλος 7", "'Αθλος 8", "'Αθλος 9", "'Αθλος 10", "'Αθλος 11", "'Αθλος 12" }));
        jComboBox14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox14ActionPerformed(evt);
            }
        });
        add(jComboBox14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 90, -1));

        jTextArea1.setBackground(new java.awt.Color(204, 51, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("1. Λιοντάρι της Νεμέας\n2. Λερναία Ύδρα\n3. Κερυνίτιδα Έλαφος\n4. Ερυμάνθιος Κάρπος\n5. Κόπρος του Αυγεία\n6. Στυμφαλίδες Όρνιθες\n7. Ταύρος της Κρήτης\n8. Άλογα του Διομήδη\n9. Ζώνη της Ιππολύτης\n10. Βόδια του Γηρυόνη\n11. Μήλα των Εσπερίδων\n12. Κέρβερος");
        jTextArea1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportView(jTextArea1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, 200));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesR/storyteller2.png"))); // NOI18N
        jLabel14.setText("jLabel14");
        jLabel14.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new javax.swing.ImageIcon(getClass().getResource("/ImagesR/woodFrame.jpg")))); // NOI18N
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 260, 100, 120));
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jComboBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox10ActionPerformed

    private void jComboBox13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox13ActionPerformed

    private void jComboBox14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox14ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox11;
    private javax.swing.JComboBox<String> jComboBox12;
    private javax.swing.JComboBox<String> jComboBox13;
    private javax.swing.JComboBox<String> jComboBox14;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
