/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package RiddlesFrame;

/**
 *
 * @author Archontis
 */
public class RiddlePrompt extends javax.swing.JPanel {

    /**
     * Creates new form RiddlePrompt
     */
    public RiddlePrompt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerLabel = new javax.swing.JLabel();
        commentOne = new javax.swing.JLabel();
        commentTwo = new javax.swing.JLabel();
        confirmButton = new javax.swing.JButton();
        commentOne1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(224, 151, 34));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(23, 15, 12), 5));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        headerLabel.setForeground(new java.awt.Color(255, 255, 255));
        headerLabel.setText("Καλως ηρθες στο δωμάτιο της Αιγυπτιακής Μυθολογίας");
        add(headerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        commentOne.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        commentOne.setForeground(new java.awt.Color(255, 255, 255));
        commentOne.setText("Εξερεύνησε το δωμάτιο για να τους βρείς");
        add(commentOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, -1, 50));

        commentTwo.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        commentTwo.setForeground(new java.awt.Color(255, 255, 255));
        commentTwo.setText("Μόλις τους λύσεις όλους θα σου δωθεί ένας κωδικός για να βγείς από την πόρτα.");
        add(commentTwo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, 50));

        confirmButton.setBackground(new java.awt.Color(102, 204, 0));
        confirmButton.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        confirmButton.setForeground(new java.awt.Color(255, 255, 255));
        confirmButton.setText("ΤΟ ΧΩ");
        confirmButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 0), 5));
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });
        add(confirmButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 180, 60));

        commentOne1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        commentOne1.setForeground(new java.awt.Color(255, 255, 255));
        commentOne1.setText("Το δωμάτιο αποτελείται από 4 γρίφους. ");
        add(commentOne1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_confirmButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel commentOne;
    private javax.swing.JLabel commentOne1;
    private javax.swing.JLabel commentTwo;
    private javax.swing.JButton confirmButton;
    private javax.swing.JLabel headerLabel;
    // End of variables declaration//GEN-END:variables
}
