/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package RiddlesFrame;

/**
 *
 * @author 30694
 */
public class RiddleGr4 extends javax.swing.JPanel {

    /**
     * Creates new form RiddleGr4
     */
    public RiddleGr4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        ans = new javax.swing.JTextField();
        confirm = new javax.swing.JButton();
        question = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 51, 0));
        jLabel2.setText("Ο Μύθος της Καλλιστώς");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 190, 20));

        jLabel4.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 51, 0));
        jLabel4.setText("ν");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 0, -1));

        jLabel3.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 51, 0));
        jLabel3.setText("Ο Δίας ερωτεύεται την πα");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, 20));

        jLabel5.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 51, 0));
        jLabel5.setText(" ν");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 10, 20));

        jLabel6.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 51, 0));
        jLabel6.setText("έμορφη Καλλιστώ, κόρη του βασιλιά της Αρκαδίας Λυκάονα, και αποκτά μαζί της έναν");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 450, 20));

        jLabel7.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 51, 0));
        jLabel7.setText("γιο, τον Αρκάδα. Θυμ");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 110, 20));

        jLabel8.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 51, 0));
        jLabel8.setText("ω");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 10, 20));

        jLabel9.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 51, 0));
        jLabel9.setText("μένη η Ήρα τη μεταμορφώνει σε αρκούδα, την οποία μετά από χρόνια συναντά ο γιός");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 440, 20));

        jLabel10.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 51, 0));
        jLabel10.setText("της στο δάσος. Προσπαθεί εκείνη να τον αγκαλιάσει και τρομαγμένος  ο  Α");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 390, 20));

        jLabel11.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 51, 0));
        jLabel11.setText(" ρ");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, 10, 20));

        jLabel12.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 51, 0));
        jLabel12.setText("κάδας ετοιμάζεται να τη σκοτώσει.");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 200, 20));
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, -1));

        jLabel15.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 51, 0));
        jLabel15.setText("ί");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 270, 0, -1));

        jLabel14.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 51, 0));
        jLabel14.setText("  Επεμβαίνει  ο  Δ");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 90, 20));

        jLabel16.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 51, 0));
        jLabel16.setText(" ας και την καταστερίζει -την ανεβάζει στον ουρανό- ως τον αστερισμό της Μεγάλης Άρκτου, καθώς");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 530, 20));

        jLabel17.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(153, 51, 0));
        jLabel17.setText("ί");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 10, 20));

        jLabel18.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(153, 51, 0));
        jLabel18.setText("επίσης και τον γιό της να την ακολουθεί ως Μικρή Άρκτος.");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 310, 20));

        ans.setBackground(new java.awt.Color(255, 204, 153));
        ans.setForeground(new java.awt.Color(102, 0, 0));
        ans.setText(" ...Type here...");
        ans.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new javax.swing.ImageIcon(getClass().getResource("/ImagesR/woodFrame.jpg")))); // NOI18N
        ans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ansActionPerformed(evt);
            }
        });
        add(ans, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, 170, 40));

        confirm.setBackground(new java.awt.Color(102, 0, 0));
        confirm.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        confirm.setForeground(new java.awt.Color(255, 204, 153));
        confirm.setText("OK");
        add(confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 460, -1, -1));

        question.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        question.setForeground(new java.awt.Color(153, 51, 0));
        question.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesR/riddleGr4_woBack_1.png"))); // NOI18N
        add(question, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 870, 500));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesR/storyteller1-removebg.png"))); // NOI18N
        jLabel19.setText("jLabel19");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, 210, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void ansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ansActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ansActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ans;
    private javax.swing.JButton confirm;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel question;
    // End of variables declaration//GEN-END:variables
}
