/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package RiddlesFrame;

/**
 *
 * @author 30694
 */
public class RiddleGr3 extends javax.swing.JPanel {

    /**
     * Creates new form RiddleGr3
     */
    public RiddleGr3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        storryteller = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        question = new javax.swing.JTextArea();
        choice4 = new javax.swing.JButton();
        choice1 = new javax.swing.JButton();
        choice2 = new javax.swing.JButton();
        choice3 = new javax.swing.JButton();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesR/286884671_718981529331721_7160274517225270454_n.png"))); // NOI18N
        jLabel2.setText("question");

        setBackground(new java.awt.Color(255, 204, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        storryteller.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesR/storyteller1.png"))); // NOI18N
        storryteller.setText("jLabel1");
        storryteller.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new javax.swing.ImageIcon(getClass().getResource("/ImagesR/woodFrame.jpg")))); // NOI18N
        add(storryteller, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, 210, 250));

        jPanel1.setBackground(new java.awt.Color(204, 153, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new javax.swing.ImageIcon(getClass().getResource("/ImagesR/woodFrame.jpg")))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        question.setBackground(new java.awt.Color(255, 204, 153));
        question.setColumns(20);
        question.setForeground(new java.awt.Color(0, 0, 0));
        question.setRows(5);
        question.setText("\"Κάποτε ήμουν ένα όμορφο κορίτσι.\n  Έκανα το λάθος να εξοργίσω την Αθηνά και τώρα είμαι ένα άσχημο τέρας. \n  Ποια είμαι;\"");
        question.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new javax.swing.ImageIcon(getClass().getResource("/ImagesR/woodFrame.jpg")))); // NOI18N
        jScrollPane1.setViewportView(question);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 430, -1));

        choice4.setBackground(new java.awt.Color(255, 204, 153));
        choice4.setForeground(new java.awt.Color(0, 0, 0));
        choice4.setText("Αίγινα");
        choice4.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new javax.swing.ImageIcon(getClass().getResource("/ImagesR/woodFrame.jpg")))); // NOI18N
        choice4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choice4ActionPerformed(evt);
            }
        });
        jPanel1.add(choice4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 130, 40));

        choice1.setBackground(new java.awt.Color(255, 204, 153));
        choice1.setForeground(new java.awt.Color(0, 0, 0));
        choice1.setText("Πανδώρα");
        choice1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new javax.swing.ImageIcon(getClass().getResource("/ImagesR/woodFrame.jpg")))); // NOI18N
        choice1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choice1ActionPerformed(evt);
            }
        });
        jPanel1.add(choice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 130, 40));

        choice2.setBackground(new java.awt.Color(255, 204, 153));
        choice2.setForeground(new java.awt.Color(0, 0, 0));
        choice2.setText("Δήμητρα");
        choice2.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new javax.swing.ImageIcon(getClass().getResource("/ImagesR/woodFrame.jpg")))); // NOI18N
        choice2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choice2ActionPerformed(evt);
            }
        });
        jPanel1.add(choice2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 130, 40));

        choice3.setBackground(new java.awt.Color(255, 204, 153));
        choice3.setForeground(new java.awt.Color(0, 0, 0));
        choice3.setText("Μέδουσα");
        choice3.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new javax.swing.ImageIcon(getClass().getResource("/ImagesR/woodFrame.jpg")))); // NOI18N
        choice3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choice3ActionPerformed(evt);
            }
        });
        jPanel1.add(choice3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 130, 40));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 590, 320));
    }// </editor-fold>//GEN-END:initComponents

    private void choice4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choice4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_choice4ActionPerformed

    private void choice1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choice1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_choice1ActionPerformed

    private void choice2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choice2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_choice2ActionPerformed

    private void choice3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choice3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_choice3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton choice1;
    private javax.swing.JButton choice2;
    private javax.swing.JButton choice3;
    private javax.swing.JButton choice4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea question;
    private javax.swing.JLabel storryteller;
    // End of variables declaration//GEN-END:variables
}
