/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package RiddlesFrame;

/**
 *
 * @author 30694
 */
public class RiddleEg3 extends javax.swing.JPanel {

    /**
     * Creates new form RiddleEg3
     */
    public RiddleEg3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        crossword = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 102, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesR/storyteller1.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new javax.swing.ImageIcon(getClass().getResource("/ImagesR/EgFrame.jpg")))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(837, 10, 210, 250));
        jLabel1.getAccessibleContext().setAccessibleName("archaeologist");

        crossword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesR/crossword1.jpg"))); // NOI18N
        add(crossword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, -1));

        jLabel3.setForeground(new java.awt.Color(102, 51, 0));
        jLabel3.setText("1. Θεός του θανάτου και της ανάστασης, βασιλιάς του Κάτω Κόσμου ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel4.setForeground(new java.awt.Color(102, 51, 0));
        jLabel4.setText("και αυτός που καθιστά δυνατή τη βλάστηση, θεός ήλιος");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel5.setForeground(new java.awt.Color(102, 51, 0));
        jLabel5.setText("και των θεός των ψυχών των νεκρών.");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new javax.swing.ImageIcon(getClass().getResource("/ImagesR/EgFrame.jpg")))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(153, 102, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setBackground(new java.awt.Color(255, 255, 153));
        jTextField1.setForeground(new java.awt.Color(102, 51, 0));
        jTextField1.setText(" type here...");
        jTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new javax.swing.ImageIcon(getClass().getResource("/ImagesR/EgFrame.jpg")))); // NOI18N
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 130, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 440, 90));

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new javax.swing.ImageIcon(getClass().getResource("/ImagesR/EgFrame.jpg")))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setForeground(new java.awt.Color(102, 51, 0));
        jLabel6.setText("5. Θεός που χαρακτηρίζεται από βία, χάος και ισχύ, συνδέεται με την έρημο.");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 16, -1, -1));

        jTextField2.setBackground(new java.awt.Color(255, 255, 153));
        jTextField2.setForeground(new java.awt.Color(102, 51, 0));
        jTextField2.setText(" type here...");
        jTextField2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new javax.swing.ImageIcon(getClass().getResource("/ImagesR/EgFrame.jpg")))); // NOI18N
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 130, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new javax.swing.ImageIcon(getClass().getResource("/ImagesR/EgFrame.jpg")))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setForeground(new java.awt.Color(102, 51, 0));
        jLabel8.setText("3. Θεός/θεά της βαλσάμωσης και προστάτης των νεκρών");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 16, -1, -1));

        jTextField4.setBackground(new java.awt.Color(255, 255, 153));
        jTextField4.setForeground(new java.awt.Color(102, 51, 0));
        jTextField4.setText(" type here...");
        jTextField4.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new javax.swing.ImageIcon(getClass().getResource("/ImagesR/EgFrame.jpg")))); // NOI18N
        jPanel4.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 130, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, 440, 70));

        jLabel11.setForeground(new java.awt.Color(102, 51, 0));
        jLabel11.setText("Δολοφόνος του Όσιρι και εχθρός του Ώρου, αλλά επίσης υποστηριχτής του");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 410, -1));

        jPanel7.setBackground(new java.awt.Color(255, 255, 153));
        jPanel7.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new javax.swing.ImageIcon(getClass().getResource("/ImagesR/EgFrame.jpg")))); // NOI18N
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setForeground(new java.awt.Color(102, 51, 0));
        jLabel12.setText("4. Σύζυγος και αδελφή του Όσιρι και μητέρα του Ώρου, συνδέεται με τα ");
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 16, -1, -1));

        jTextField7.setBackground(new java.awt.Color(255, 255, 153));
        jTextField7.setForeground(new java.awt.Color(102, 51, 0));
        jTextField7.setText(" type here...");
        jTextField7.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new javax.swing.ImageIcon(getClass().getResource("/ImagesR/EgFrame.jpg")))); // NOI18N
        jPanel7.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 130, -1));

        jPanel8.setBackground(new java.awt.Color(255, 255, 153));
        jPanel8.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new javax.swing.ImageIcon(getClass().getResource("/ImagesR/EgFrame.jpg")))); // NOI18N
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setForeground(new java.awt.Color(102, 51, 0));
        jLabel13.setText("3. Θεός/θεά της βαλσάμωσης και προστάτης των νεκρών");
        jPanel8.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 16, -1, -1));

        jTextField8.setBackground(new java.awt.Color(255, 255, 153));
        jTextField8.setForeground(new java.awt.Color(102, 51, 0));
        jTextField8.setText(" type here...");
        jTextField8.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new javax.swing.ImageIcon(getClass().getResource("/ImagesR/EgFrame.jpg")))); // NOI18N
        jPanel8.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 130, -1));

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, 440, 70));

        jLabel14.setForeground(new java.awt.Color(102, 51, 0));
        jLabel14.setText("ταφικά τελετουργικά, τη μητρότητα, την προστασία και τη μαγεία.");
        jPanel7.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 410, -1));

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, 440, 100));

        jLabel21.setForeground(new java.awt.Color(102, 51, 0));
        jLabel21.setText("(εκάστοτε) βασιλιά.");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 46, -1, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 520, 440, 90));

        jPanel3.setBackground(new java.awt.Color(255, 255, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new javax.swing.ImageIcon(getClass().getResource("/ImagesR/EgFrame.jpg")))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setForeground(new java.awt.Color(102, 51, 0));
        jLabel7.setText("2. Θεός του Ήλιου.");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 16, -1, -1));

        jTextField3.setBackground(new java.awt.Color(255, 255, 153));
        jTextField3.setForeground(new java.awt.Color(102, 51, 0));
        jTextField3.setText(" type here...");
        jTextField3.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new javax.swing.ImageIcon(getClass().getResource("/ImagesR/EgFrame.jpg")))); // NOI18N
        jPanel3.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 130, -1));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 440, 70));

        jPanel5.setBackground(new java.awt.Color(255, 255, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new javax.swing.ImageIcon(getClass().getResource("/ImagesR/EgFrame.jpg")))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setForeground(new java.awt.Color(102, 51, 0));
        jLabel9.setText("3. Θεός/θεά της βαλσάμωσης και προστάτης των νεκρών");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 16, -1, -1));

        jTextField5.setBackground(new java.awt.Color(255, 255, 153));
        jTextField5.setForeground(new java.awt.Color(102, 51, 0));
        jTextField5.setText(" type here...");
        jTextField5.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new javax.swing.ImageIcon(getClass().getResource("/ImagesR/EgFrame.jpg")))); // NOI18N
        jPanel5.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 130, -1));

        jPanel6.setBackground(new java.awt.Color(255, 255, 153));
        jPanel6.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new javax.swing.ImageIcon(getClass().getResource("/ImagesR/EgFrame.jpg")))); // NOI18N
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setForeground(new java.awt.Color(102, 51, 0));
        jLabel10.setText("3. Θεός/θεά της βαλσάμωσης και προστάτης των νεκρών");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 16, -1, -1));

        jTextField6.setBackground(new java.awt.Color(255, 255, 153));
        jTextField6.setForeground(new java.awt.Color(102, 51, 0));
        jTextField6.setText(" type here...");
        jTextField6.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new javax.swing.ImageIcon(getClass().getResource("/ImagesR/EgFrame.jpg")))); // NOI18N
        jPanel6.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 130, -1));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, 440, 70));

        add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 440, 70));

        jPanel9.setBackground(new java.awt.Color(255, 255, 153));
        jPanel9.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new javax.swing.ImageIcon(getClass().getResource("/ImagesR/EgFrame.jpg")))); // NOI18N
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setForeground(new java.awt.Color(102, 51, 0));
        jLabel15.setText("4. Σύζυγος και αδελφή του Όσιρι και μητέρα του Ώρου, συνδέεται με τα ");
        jPanel9.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 16, -1, -1));

        jTextField9.setBackground(new java.awt.Color(255, 255, 153));
        jTextField9.setForeground(new java.awt.Color(102, 51, 0));
        jTextField9.setText(" type here...");
        jTextField9.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new javax.swing.ImageIcon(getClass().getResource("/ImagesR/EgFrame.jpg")))); // NOI18N
        jPanel9.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 130, -1));

        jPanel10.setBackground(new java.awt.Color(255, 255, 153));
        jPanel10.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new javax.swing.ImageIcon(getClass().getResource("/ImagesR/EgFrame.jpg")))); // NOI18N
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setForeground(new java.awt.Color(102, 51, 0));
        jLabel16.setText("3. Θεός/θεά της βαλσάμωσης και προστάτης των νεκρών");
        jPanel10.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 16, -1, -1));

        jTextField10.setBackground(new java.awt.Color(255, 255, 153));
        jTextField10.setForeground(new java.awt.Color(102, 51, 0));
        jTextField10.setText(" type here...");
        jTextField10.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new javax.swing.ImageIcon(getClass().getResource("/ImagesR/EgFrame.jpg")))); // NOI18N
        jPanel10.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 130, -1));

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, 440, 70));

        jLabel17.setForeground(new java.awt.Color(102, 51, 0));
        jLabel17.setText("ταφικά τελετουργικά, τη μητρότητα, την προστασία και τη μαγεία.");
        jPanel9.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 410, -1));

        jPanel11.setBackground(new java.awt.Color(255, 255, 153));
        jPanel11.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new javax.swing.ImageIcon(getClass().getResource("/ImagesR/EgFrame.jpg")))); // NOI18N
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setForeground(new java.awt.Color(102, 51, 0));
        jLabel18.setText("4. Σύζυγος και αδελφή του Όσιρι και μητέρα του Ώρου, συνδέεται με τα ");
        jPanel11.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 16, -1, -1));

        jTextField11.setBackground(new java.awt.Color(255, 255, 153));
        jTextField11.setForeground(new java.awt.Color(102, 51, 0));
        jTextField11.setText(" type here...");
        jTextField11.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new javax.swing.ImageIcon(getClass().getResource("/ImagesR/EgFrame.jpg")))); // NOI18N
        jPanel11.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 130, -1));

        jPanel12.setBackground(new java.awt.Color(255, 255, 153));
        jPanel12.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new javax.swing.ImageIcon(getClass().getResource("/ImagesR/EgFrame.jpg")))); // NOI18N
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setForeground(new java.awt.Color(102, 51, 0));
        jLabel19.setText("3. Θεός/θεά της βαλσάμωσης και προστάτης των νεκρών");
        jPanel12.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 16, -1, -1));

        jTextField12.setBackground(new java.awt.Color(255, 255, 153));
        jTextField12.setForeground(new java.awt.Color(102, 51, 0));
        jTextField12.setText(" type here...");
        jTextField12.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new javax.swing.ImageIcon(getClass().getResource("/ImagesR/EgFrame.jpg")))); // NOI18N
        jPanel12.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 130, -1));

        jPanel11.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, 440, 70));

        jLabel20.setForeground(new java.awt.Color(102, 51, 0));
        jLabel20.setText("ταφικά τελετουργικά, τη μητρότητα, την προστασία και τη μαγεία.");
        jPanel11.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 410, -1));

        jPanel9.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, 440, 100));

        add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, 440, 100));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel crossword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
