/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package RiddlesFrame;

/**
 *
 * @author 30694
 */
public class RiddleEg3 extends javax.swing.JPanel {

    /**
     * Creates new form RiddleEg3
     */
    public RiddleEg3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        storytellerLabel = new javax.swing.JLabel();
        crossword = new javax.swing.JLabel();
        wrongLabel = new javax.swing.JLabel();
        questOnePanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        input1 = new javax.swing.JTextField();
        questTwoPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        input2 = new javax.swing.JTextField();
        questThreePanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        input3 = new javax.swing.JTextField();
        questFourPanel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        input4 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        questFivePanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        input5 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 102, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        storytellerLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesR/storyteller1.png"))); // NOI18N
        storytellerLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new javax.swing.ImageIcon(getClass().getResource("/ImagesR/EgFrame.jpg")))); // NOI18N
        add(storytellerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 210, 250));
        storytellerLabel.getAccessibleContext().setAccessibleName("archaeologist");

        crossword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesR/crossword1.jpg"))); // NOI18N
        add(crossword, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 320, -1));

        wrongLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        wrongLabel.setForeground(new java.awt.Color(255, 51, 51));
        wrongLabel.setText("ΛΑΘΟΣ");
        wrongLabel.setVisible(false);
        add(wrongLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, -1, -1));

        questOnePanel.setBackground(new java.awt.Color(255, 255, 153));
        questOnePanel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new javax.swing.ImageIcon(getClass().getResource("/ImagesR/EgFrame.jpg")))); // NOI18N
        questOnePanel.setForeground(new java.awt.Color(153, 102, 0));
        questOnePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setForeground(new java.awt.Color(102, 51, 0));
        jLabel5.setText("και των θεός των ψυχών των νεκρών.");
        questOnePanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 50, 220, -1));

        jLabel4.setForeground(new java.awt.Color(102, 51, 0));
        jLabel4.setText("και αυτός που καθιστά δυνατή τη βλάστηση, θεός ήλιος");
        questOnePanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel3.setForeground(new java.awt.Color(102, 51, 0));
        jLabel3.setText("1. Θεός του θανάτου και της ανάστασης, βασιλιάς του Κάτω Κόσμου ");
        questOnePanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        input1.setBackground(new java.awt.Color(255, 255, 153));
        input1.setForeground(new java.awt.Color(102, 51, 0));
        input1.setText(" type here...");
        input1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new javax.swing.ImageIcon(getClass().getResource("/ImagesR/EgFrame.jpg")))); // NOI18N
        questOnePanel.add(input1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 130, -1));

        add(questOnePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 440, 90));

        questTwoPanel.setBackground(new java.awt.Color(255, 255, 153));
        questTwoPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new javax.swing.ImageIcon(getClass().getResource("/ImagesR/EgFrame.jpg")))); // NOI18N
        questTwoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setForeground(new java.awt.Color(102, 51, 0));
        jLabel7.setText("2. Θεός του Ήλιου.");
        questTwoPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 16, -1, -1));

        input2.setBackground(new java.awt.Color(255, 255, 153));
        input2.setForeground(new java.awt.Color(102, 51, 0));
        input2.setText(" type here...");
        input2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new javax.swing.ImageIcon(getClass().getResource("/ImagesR/EgFrame.jpg")))); // NOI18N
        questTwoPanel.add(input2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 130, -1));

        add(questTwoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 440, 70));

        questThreePanel.setBackground(new java.awt.Color(255, 255, 153));
        questThreePanel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new javax.swing.ImageIcon(getClass().getResource("/ImagesR/EgFrame.jpg")))); // NOI18N
        questThreePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setForeground(new java.awt.Color(102, 51, 0));
        jLabel9.setText("3. Θεός/θεά της βαλσάμωσης και προστάτης των νεκρών");
        questThreePanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 16, -1, -1));

        input3.setBackground(new java.awt.Color(255, 255, 153));
        input3.setForeground(new java.awt.Color(102, 51, 0));
        input3.setText(" type here...");
        input3.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new javax.swing.ImageIcon(getClass().getResource("/ImagesR/EgFrame.jpg")))); // NOI18N
        questThreePanel.add(input3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 130, -1));

        add(questThreePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 440, 70));

        questFourPanel.setBackground(new java.awt.Color(255, 255, 153));
        questFourPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new javax.swing.ImageIcon(getClass().getResource("/ImagesR/EgFrame.jpg")))); // NOI18N
        questFourPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setForeground(new java.awt.Color(102, 51, 0));
        jLabel15.setText("4. Σύζυγος και αδελφή του Όσιρι και μητέρα του Ώρου, συνδέεται με τα ");
        questFourPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 16, -1, -1));

        input4.setBackground(new java.awt.Color(255, 255, 153));
        input4.setForeground(new java.awt.Color(102, 51, 0));
        input4.setText(" type here...");
        input4.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new javax.swing.ImageIcon(getClass().getResource("/ImagesR/EgFrame.jpg")))); // NOI18N
        questFourPanel.add(input4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 130, -1));

        jLabel17.setForeground(new java.awt.Color(102, 51, 0));
        jLabel17.setText("ταφικά τελετουργικά, τη μητρότητα, την προστασία και τη μαγεία.");
        questFourPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 410, -1));

        add(questFourPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 440, 100));

        questFivePanel.setBackground(new java.awt.Color(255, 255, 153));
        questFivePanel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new javax.swing.ImageIcon(getClass().getResource("/ImagesR/EgFrame.jpg")))); // NOI18N
        questFivePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setForeground(new java.awt.Color(102, 51, 0));
        jLabel6.setText("5. Θεός που χαρακτηρίζεται από βία, χάος και ισχύ, συνδέεται με την έρημο.");
        questFivePanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 16, -1, -1));

        input5.setBackground(new java.awt.Color(255, 255, 153));
        input5.setForeground(new java.awt.Color(102, 51, 0));
        input5.setText(" type here...");
        input5.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new javax.swing.ImageIcon(getClass().getResource("/ImagesR/EgFrame.jpg")))); // NOI18N
        questFivePanel.add(input5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 130, -1));

        jLabel11.setForeground(new java.awt.Color(102, 51, 0));
        jLabel11.setText("Δολοφόνος του Όσιρι και εχθρός του Ώρου, αλλά επίσης υποστηριχτής του");
        questFivePanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 410, -1));

        jLabel21.setForeground(new java.awt.Color(102, 51, 0));
        jLabel21.setText("(εκάστοτε) βασιλιά.");
        questFivePanel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 46, -1, -1));

        add(questFivePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 440, 90));

        submitButton.setText("ΥΠΟΒΟΛΗ");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 510, 130, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // Get User Input
        String answer1 = this.input1.getText();
        String answer2 = this.input2.getText();
        String answer3 = this.input3.getText();
        String answer4 = this.input4.getText();
        String answer5 = this.input5.getText();
        
        // Check input
        if(answer1.equalsIgnoreCase("RA") && answer2.equalsIgnoreCase("ANUBIS") && answer3.equalsIgnoreCase("OSIRIS") && answer4.equalsIgnoreCase("ISIS") && answer5.equalsIgnoreCase("SETH")){
            this.setVisible(false);
        }
    }//GEN-LAST:event_submitButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel crossword;
    private javax.swing.JTextField input1;
    private javax.swing.JTextField input2;
    private javax.swing.JTextField input3;
    private javax.swing.JTextField input4;
    private javax.swing.JTextField input5;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel questFivePanel;
    private javax.swing.JPanel questFourPanel;
    private javax.swing.JPanel questOnePanel;
    private javax.swing.JPanel questThreePanel;
    private javax.swing.JPanel questTwoPanel;
    private javax.swing.JLabel storytellerLabel;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel wrongLabel;
    // End of variables declaration//GEN-END:variables
}
